semana8/mvc/app/models/user_model.py
from database import db
from datetime import datetime
class User(db.Model):
    __tablename__ = 'users'
    
    id = db.Column(db.Integer, primary_key=True)
    first_name = db.Column(db.String(50), nullable = False)
    last_name = db.Column(db.String(50), nullable=False)
    email = db.Column(db.String(50), nullable=False)
    password = db.Column(db.String(50), nullable=False)
    birthdate=db.Column(db.String(50), nullable=False)
    
    def __init__(self, first_name, last_name, email, password, birthdate):
        self.first_name = first_name
        self.last_name = last_name
        self.email = email
        self.password= password
        self.birthdate = datetime.strptime(birthdate,"%Y-%m-%d").date()
        
    def save(self):
        db.session.add(self)
        db.session.commit()
        
    @staticmethod
    def get_all():
        return User.query.all()

semana8/mvc/app/controllers/user_controller.py
from flask import Blueprint, request, redirect, url_for

from views import user_view

from models.user_model import User

user_bp = Blueprint('user', __name__)

@user_bp.route('/')
def usuarios():
    users = User.get_all()
    return user_view.usuarios(users)

@user_bp.route('/users', methods=['GET', 'POST'])
def registro():
    if request.method == 'POST':
        first_name = request.form['first_name']
        last_name = request.form['last_name']
        email = request.form['email']
        password = request.form['password']
        birthdate = request.form['birthdate']
        
        user = User(first_name, last_name, email, password, birthdate)
        user.save()
        
        return redirect(url_for('user.usuarios'))
    return user_view.registro()

semana8/mvc/app/views/user_view.py
#render_template, Funcion que permite como renderizar la pagina 
from flask import render_template

def usuarios(users):
    return render_template("usuarios.html", users=users)

def registro():
    return render_template("registro.html")

semana8/mvc/app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>MVC</title>
</head>
<body>
    <h1>MVC</h1>
    <nav>
        <a href="{{ url_for('user.registro') }}">Registrar Usuarios</a>
        <a href="{{ url_for('user.usuarios') }}">Lista de Usuarios</a>
    </nav>
    <div>
        {% block content %}
        
        {% endblock %}
    </div>
</body>
</html>

semana8/mvc/app/templates/registro.html
{% extends 'base.html' %}

{% block content %}
<h2>Registrar Usuario</h2>
<form method="post">
    <label for="first_name">Nombre:</label>
    <input type="text" id="first_name" name="first_name" required><br>
    <label for="last_name">Apellido:</label>
    <input type="text" id="last_name" name="last_name" required><br>
    <label for="email">Email:</label>
    <input type="text" id="email" name="email" required><br>
    <label for="password">Password:</label>
    <input type="text" id="password" name="password" required"><br>
    <label for="birthdate">Fecha de nacimiento:</label>
    <input type="date" id="birthdate" name="birthdate" required><br>
    <input type="submit" value="Registrar">
</form>
{% endblock %}

semana8/mvc/app/templates/usuarios.html
{% extends 'base.html' %}

{% block content %}
<h2>Lista de Usuarios</h2>
<ul>
    {% for user in users %}
        <li>{{ user.first_name }} {{ user.last_name }} {{ user.email }} {{ user.password }} {{user.birthdate}}</li>
    {% endfor %}
</ul>
{% endblock %}